import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
import LoginBtn from "./loginBtn";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import { getServerSession } from "next-auth";
import LogoutBtn from "./logoutBtn";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next.js로 만드는 게시판",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);

  // console.log(session);

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navbar">
          <Link href="/" className="logo">
            App Forum
          </Link>
          <Link href="/list">List</Link>
          {session ? <Link href="/write">Write</Link> : <></>}
          {session ? (
            <span>
              {session.user.name} <LogoutBtn />
            </span>
          ) : (
            <LoginBtn />
          )}
        </div>
        {children}
      </body>
    </html>
  );
}
